//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise.Models
{
    using System;
    
    [Flags]
    public enum CourseType : int
    {
        Python = 1,
        C_Sharp = 2,
        HTML = 4,
        CSS = 8,
        JavaScript = 16,
        Java = 32,
        Kotlin = 64
    }
}
